-- ============================================================================
-- SAT-7 Production Booking — Seed / demo data
-- Safe to run repeatedly (idempotent via on conflict do nothing).
-- Demo ACCOUNTS must be created via the Auth signup flow (the admin user flow
-- in Settings, or app signup) and then promoted; raw auth.users inserts often
-- cannot log in. The rows below are data FKs only.
-- ============================================================================

-- Channels
insert into public.channels (id, name) values
  ('11111111-1111-1111-1111-111111111101', 'SAT-7')
on conflict (id) do nothing;
insert into public.channels (id, name) values
  ('11111111-1111-1111-1111-111111111102', 'SAT-7 ARABIC')
on conflict (id) do nothing;
insert into public.channels (id, name) values
  ('11111111-1111-1111-1111-111111111103', 'SAT-7 KIDS')
on conflict (id) do nothing;
insert into public.channels (id, name) values
  ('11111111-1111-1111-1111-111111111104', 'SAT-7 PLUS')
on conflict (id) do nothing;

-- Locations
insert into public.locations (id, name, address) values
  ('22222222-2222-2222-2222-222222222201', 'Studio A — Cairo', 'Cairo Media City')
on conflict (id) do nothing;
insert into public.locations (id, name, address) values
  ('22222222-2222-2222-2222-222222222202', 'Studio B — Beirut', 'Beirut Tower')
on conflict (id) do nothing;
insert into public.locations (id, name, address) values
  ('22222222-2222-2222-2222-222222222203', 'OB Site — Amman', 'Amman Outdoor')
on conflict (id) do nothing;
insert into public.locations (id, name, address) values
  ('22222222-2222-2222-2222-222222222204', 'Outdoor OBVAN', 'OBVAN')
on conflict (id) do nothing;

-- People
insert into public.people (id, full_name, whatsapp, email, department, company, notes) values
  ('33333333-3333-3333-3333-333333333301', 'Nadine Haddad', '+201000000001', 'nadine@sat7.org', 'Host', 'SAT-7', 'Lead presenter')
on conflict (id) do nothing;
insert into public.people (id, full_name, whatsapp, email, department, company, notes) values
  ('33333333-3333-3333-3333-333333333302', 'Karim Mansour', '+201000000002', 'karim@sat7.org', 'Guest', 'Partner Org', 'Recurring guest')
on conflict (id) do nothing;
insert into public.people (id, full_name, whatsapp, email, department, company, notes) values
  ('33333333-3333-3333-3333-333333333303', 'Layla Fares', '+201000000003', 'layla@sat7.org', 'Co-Host', 'SAT-7', null)
on conflict (id) do nothing;

-- Programs
insert into public.programs (id, name, channel_id, company, default_location, default_place_in, default_top_camera, notes) values
  ('44444444-4444-4444-4444-444444444401', 'Evening Hour', '11111111-1111-1111-1111-111111111101', 'SAT-7', 'Studio A — Cairo', 'Main floor', 'Balcony cam 2', 'Flagship talk show')
on conflict (id) do nothing;
insert into public.programs (id, name, channel_id, company, default_location, default_place_in, default_top_camera, notes) values
  ('44444444-4444-4444-4444-444444444402', 'Kids Club Live', '11111111-1111-1111-1111-111111111103', 'SAT-7', 'Studio B — Beirut', 'Stage left', 'Crane cam', null)
on conflict (id) do nothing;
insert into public.programs (id, name, channel_id, company, default_location, default_place_in, default_top_camera, notes) values
  ('44444444-4444-4444-4444-444444444403', 'Documentary Special', '11111111-1111-1111-1111-111111111104', 'SAT-7 PLUS', 'OB Site — Amman', 'Field', 'Handheld', 'Field production')
on conflict (id) do nothing;

-- Sample bookings (booking_number is auto-generated by trigger; leave it null)
insert into public.bookings (id, person_id, program_id, channel_id, production_date, call_time, start_time, end_time, live_recorded, episode_number, location_id, confirmation_status, extra_notes)
values
  ('55555555-5555-5555-5555-555555555501', '33333333-3333-3333-3333-333333333301', '44444444-4444-4444-4444-444444444401', '11111111-1111-1111-1111-111111111101', current_date + 1, '14:00', '15:00', '16:30', 'Live', 'EP-204', '22222222-2222-2222-2222-222222222201', 'Pending Confirmation', 'Arrive 1h before call time'),
  ('55555555-5555-5555-5555-555555555502', '33333333-3333-3333-3333-333333333302', '44444444-4444-4444-4444-444444444402', '11111111-1111-1111-1111-111111111103', current_date + 3, '09:00', '10:00', '11:00', 'Recorded', 'EP-88', '22222222-2222-2222-2222-222222222202', 'Confirmed', null),
  ('55555555-5555-5555-5555-555555555503', '33333333-3333-3333-3333-333333333303', '44444444-4444-4444-4444-444444444403', '11111111-1111-1111-1111-111111111104', current_date + 5, '07:30', '08:00', '18:00', 'Recorded', 'DOC-12', '22222222-2222-2222-2222-222222222203', 'Reschedule Requested', 'Weather dependent')
on conflict (id) do nothing;

-- Child rows for sample bookings
insert into public.production_requirements (booking_id, place_in, place_in_time, place_in_location, top_camera, top_camera_time, top_camera_location)
values
  ('55555555-5555-5555-5555-555555555501', 'Main floor', '14:45', 'Studio A', 'Balcony cam 2', '15:00', 'Booth')
on conflict do nothing;

insert into public.transportation (booking_id, type, departure_time, pickup_location, driver, notes)
values
  ('55555555-5555-5555-5555-555555555501', 'Car', '13:00', 'Hotel', 'Ramy', 'VIP guest')
on conflict do nothing;

insert into public.dress_codes (booking_id, code, notes)
values
  ('55555555-5555-5555-5555-555555555501', 'TV Appropriate', 'Brand colors preferred')
on conflict do nothing;

insert into public.booking_activity (booking_id, action, description)
values
  ('55555555-5555-5555-5555-555555555501', 'Booking created', 'Booking created from wizard')
on conflict do nothing;

-- Ensure org settings row exists with sensible defaults
insert into public.org_settings (id, org_name, booking_prefix, time_zone, date_format, default_booking_duration)
values ('00000000-0000-0000-0000-000000000001', 'SAT-7 Production', 'SAT7', 'Africa/Cairo', 'MMM d, yyyy', 120)
on conflict (id) do nothing;
