"use server";

import { createAdminClient } from "@/lib/supabase/admin";
import { getCurrentUser } from "@/lib/auth";
import type {
  Booking,
  Person,
  Program,
  ProductionRequirement,
  Transportation,
  DressCode,
} from "@/lib/types";

export interface BookingFormState {
  ok: boolean;
  message: string;
  bookingId?: string;
}

export interface BookingInput {
  person_id: string | null;
  program_id: string | null;
  channel_id: string | null;
  production_date: string | null;
  call_time: string | null;
  start_time: string | null;
  end_time: string | null;
  live_recorded: "Live" | "Recorded";
  episode_number: string | null;
  recorded_episodes_count: number | null;
  location_id: string | null;
  extra_notes: string | null;
  requirements?: {
    place_in?: string | null;
    place_in_time?: string | null;
    place_in_location?: string | null;
    place_in_notes?: string | null;
    top_camera?: string | null;
    top_camera_time?: string | null;
    top_camera_location?: string | null;
    top_camera_notes?: string | null;
  };
  transportation?: {
    type: string;
    departure_time?: string | null;
    pickup_location?: string | null;
    driver?: string | null;
    notes?: string | null;
  };
  dress_code?: { code: string; notes?: string | null };
}

/**
 * Detect scheduling conflicts: same person, same production_date, overlapping
 * call time window (call_time +/- 4h heuristic), excluding a given booking id.
 */
export async function detectConflict(
  personId: string | null,
  productionDate: string | null,
  excludeBookingId?: string,
): Promise<{ conflict: boolean; reason?: string; existing?: Booking }> {
  if (!personId || !productionDate) return { conflict: false };
  const sb = createAdminClient();
  let q = sb
    .from("bookings")
    .select("*")
    .eq("person_id", personId)
    .eq("production_date", productionDate)
    .neq("confirmation_status", "Cancelled");
  if (excludeBookingId) q = q.neq("id", excludeBookingId);
  const { data } = await q;
  if (data && data.length > 0) {
    const ex = data[0] as Booking;
    return {
      conflict: true,
      reason: `This guest already has a booking on ${productionDate} (${ex.call_time ?? "—"} — ${ex.booking_number}).`,
      existing: ex,
    };
  }
  return { conflict: false };
}

export async function createBooking(input: BookingInput): Promise<BookingFormState> {
  const user = await getCurrentUser();
  if (!user) return { ok: false, message: "You must be signed in." };

  const sb = createAdminClient();
  const { data: booking, error } = await sb
    .from("bookings")
    .insert({
      person_id: input.person_id,
      program_id: input.program_id,
      channel_id: input.channel_id,
      production_date: input.production_date,
      call_time: input.call_time,
      start_time: input.start_time,
      end_time: input.end_time,
      live_recorded: input.live_recorded,
      episode_number: input.episode_number,
      recorded_episodes_count: input.recorded_episodes_count,
      location_id: input.location_id,
      extra_notes: input.extra_notes,
      created_by: user.id,
      confirmation_status: "Pending Confirmation",
      // booking_number auto-generated by trigger
    })
    .select("id")
    .single();

  if (error) return { ok: false, message: error.message };
  const bookingId = (booking as { id: string }).id;

  // child rows
  if (input.requirements) {
    await sb.from("production_requirements").insert({
      booking_id: bookingId,
      ...input.requirements,
    });
  }
  if (input.transportation) {
    await sb.from("transportation").insert({ booking_id: bookingId, ...input.transportation });
  }
  if (input.dress_code) {
    await sb.from("dress_codes").insert({ booking_id: bookingId, ...input.dress_code });
  }
  await sb.from("booking_activity").insert({
    booking_id: bookingId,
    actor_id: user.id,
    action: "Booking created",
    description: `Booking created by ${user.full_name || user.email}`,
  });

  return { ok: true, message: "Booking created successfully.", bookingId };
}

export async function updateBooking(
  id: string,
  input: BookingInput,
): Promise<BookingFormState> {
  const user = await getCurrentUser();
  if (!user) return { ok: false, message: "You must be signed in." };

  const sb = createAdminClient();
  const { error } = await sb
    .from("bookings")
    .update({
      person_id: input.person_id,
      program_id: input.program_id,
      channel_id: input.channel_id,
      production_date: input.production_date,
      call_time: input.call_time,
      start_time: input.start_time,
      end_time: input.end_time,
      live_recorded: input.live_recorded,
      episode_number: input.episode_number,
      recorded_episodes_count: input.recorded_episodes_count,
      location_id: input.location_id,
      extra_notes: input.extra_notes,
    })
    .eq("id", id);

  if (error) return { ok: false, message: error.message };

  // upsert children
  if (input.requirements) {
    await sb.from("production_requirements").upsert({
      booking_id: id,
      ...input.requirements,
    });
  }
  if (input.transportation) {
    await sb.from("transportation").upsert({ booking_id: id, ...input.transportation });
  }
  if (input.dress_code) {
    await sb.from("dress_codes").upsert({ booking_id: id, ...input.dress_code });
  }
  await sb.from("booking_activity").insert({
    booking_id: id,
    actor_id: user.id,
    action: "Booking updated",
    description: `Booking updated by ${user.full_name || user.email}`,
  });

  return { ok: true, message: "Booking updated successfully.", bookingId: id };
}

export async function duplicateBooking(id: string): Promise<BookingFormState> {
  const user = await getCurrentUser();
  if (!user) return { ok: false, message: "You must be signed in." };
  const sb = createAdminClient();
  const { data: src } = await sb.from("bookings").select("*").eq("id", id).maybeSingle();
  if (!src) return { ok: false, message: "Source booking not found." };

  const { id: _, created_at, updated_at, booking_number, confirmation_status, ...rest } =
    src as Booking;
  const { data: created, error } = await sb
    .from("bookings")
    .insert({ ...rest, created_by: user.id, confirmation_status: "Pending Confirmation" })
    .select("id")
    .single();
  if (error) return { ok: false, message: error.message };
  const newId = (created as { id: string }).id;

  const [{ data: req }, { data: transp }, { data: dress }] = await Promise.all([
    sb.from("production_requirements").select("*").eq("booking_id", id).maybeSingle(),
    sb.from("transportation").select("*").eq("booking_id", id).maybeSingle(),
    sb.from("dress_codes").select("*").eq("booking_id", id).maybeSingle(),
  ]);
  if (req) {
    const { id: rid, ...r } = req as ProductionRequirement;
    await sb.from("production_requirements").insert({ ...r, booking_id: newId });
  }
  if (transp) {
    const { id: tid, ...t } = transp as Transportation;
    await sb.from("transportation").insert({ ...t, booking_id: newId });
  }
  if (dress) {
    const { id: did, ...d } = dress as any;
    await sb.from("dress_codes").insert({ ...d, booking_id: newId });
  }
  await sb.from("booking_activity").insert({
    booking_id: newId,
    actor_id: user.id,
    action: "Booking created",
    description: `Duplicated from ${booking_number}`,
  });
  return { ok: true, message: "Booking duplicated (new pending booking).", bookingId: newId };
}

export async function setBookingStatus(
  id: string,
  status: Booking["confirmation_status"],
  note?: string,
): Promise<BookingFormState> {
  const user = await getCurrentUser();
  if (!user) return { ok: false, message: "You must be signed in." };
  const sb = createAdminClient();
  const { error } = await sb.from("bookings").update({ confirmation_status: status }).eq("id", id);
  if (error) return { ok: false, message: error.message };
  await sb.from("booking_activity").insert({
    booking_id: id,
    actor_id: user.id,
    action: `Status → ${status}`,
    description: note || `Status changed to ${status} by ${user.full_name || user.email}`,
  });
  return { ok: true, message: `Status updated to ${status}.`, bookingId: id };
}

export async function cancelBooking(id: string, reason?: string): Promise<BookingFormState> {
  return setBookingStatus(id, "Cancelled", reason || "Booking cancelled.");
}
